import './stencil.core';
/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import './stencil.core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface AkAvatar {
      'image': string;
      'message': string;
    }
  }

  interface HTMLAkAvatarElement extends StencilComponents.AkAvatar, HTMLStencilElement {}

  var HTMLAkAvatarElement: {
    prototype: HTMLAkAvatarElement;
    new (): HTMLAkAvatarElement;
  };
  interface HTMLElementTagNameMap {
    'ak-avatar': HTMLAkAvatarElement;
  }
  interface ElementTagNameMap {
    'ak-avatar': HTMLAkAvatarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ak-avatar': JSXElements.AkAvatarAttributes;
    }
  }
  namespace JSXElements {
    export interface AkAvatarAttributes extends HTMLAttributes {
      'image'?: string;
      'message'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;